### ISSUE TITLE
Migrated VM has input endpoints which is not right since endpoints don't exist in ARM

### ISSUE THREAD

**Issue by singhkays** [fullscale180/asm2arm#10]
I see that the migrated VM has input endpoints in the networkProfile which is incorrect since endpoints concept does not exist in ARM. What needs to be done instead is to create NSGs and restrict access for the equivalent endpoints. Azure only checks for networkInterface id in the networkProfile and discards everything else. 

```
        "networkProfile" : {
          "networkInterfaces" : [{
              "id" : "[resourceId('Microsoft.Network/networkInterfaces','win2012kay_win2012kay_nic')]"
            }
          ],
          "inputEndpoints" : [{
              "endpointName" : "PowerShell",
              "privatePort" : 5986,
              "publicPort" : 5986,
              "protocol" : "tcp",
              "enableDirectServerReturn" : false
            }, {
              "endpointName" : "Remote Desktop",
              "privatePort" : 3389,
              "publicPort" : 61597,
              "protocol" : "tcp",
              "enableDirectServerReturn" : false
            }
          ]
        },
```

**Comment by Ercenk** [comment]
Thanks Kay for reporting this. Fixed and pushed.

**Comment by singhkays** [comment]
@Ercenk We migrated this code to https://github.com/Azure/classic-iaas-resourcemanager-migration. Can you make sure any changes made here are submitted there as well?
