### ISSUE TITLE
New-AzureRmResourceGroupDeployment : A parameter cannot be found that matches parameter name 'Location'.

### ISSUE THREAD

**Issue by MathijsHofkens** [fullscale180/asm2arm#3]
Hi

While testing your awesome script, I cannot get further than generating all necessary files.

Step 1:
"Add-AzureSMVmToRM -ServiceName ARX-MIGTST-001 -Name ARX-MIGTST-001 -ResourceGroupName MIG-ASM -DiskAction CopyDisks -OutputFileFolder C:\asmdisks -AppendTimeStampForFiles"

Step 2 (command is generated by step 1):
"New-AzureSmToRMDeployment -ResourceGroupName 'MIG-ASM' -Location 'West Europe' -ServiceName 'ARX-MIGTST-001' -Name 'ARX-MIGTST-001' -StorageAccountName 'cronosgoldsponsors00arm' -SetupTemplateFileName 'C:\asmdisks\ARX-MI
GTST-001-ARX-MIGTST-001-setup-160115-0448.json' -ParametersFileName 'C:\asmdisks\ARX-MIGTST-001-ARX-MIGTST-001-parameters-160115-0448.json' -DeployTemplateFileName 'C:\asmdisks\ARX-MIGTST-001-ARX-MIGTST-001-deploy-160115
-0448.json'  -CopyDisksScript 'C:\asmdisks\ARX-MIGTST-001-ARX-MIGTST-001-copydisks-160115-0448.ps1' -ImperativeScript 'C:\asmdisks\ARX-MIGTST-001-ARX-MIGTST-001-setextensions-160115-0448.ps1'
Same commandline can also be found in C:\asmdisks\ARX-MIGTST-001-ARX-MIGTST-001-deploy-160115-0448.ps1"

After this command powershell gives met the following error:
New-AzureRmResourceGroupDeployment : A parameter cannot be found that matches parameter name 'Location'.
At C:\Users\mathi\Google Drive\Git\azure\asm2arm\asm2arm.psm1:701 char:185
- ... ileName -TemplateParameterFile $ParametersFileName  -Location $Locati ...
-                                                         ~~~~~~~~~
  - CategoryInfo          : InvalidArgument: (:) [New-AzureRmResourceGroupDeployment], ParameterBindingException
  - FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand

What am I doing wrong?

Thanks in advance!

**Comment by AurelieGordon** [comment]
Hello,

I got exactly the same issue and finally found a solution :
replace in the file asm2arm.psm1 line 281
    $location = $cloudService.Location
by $location = $cloudService.ExtendedProperties.ResourceLocation

And reimport the module :  Import-Module .\asm2arm.psd1

Hope it will help you !

**Comment by Ercenk** [comment]
Hello,
Many thanks for testing and using our tool. I just checked that part against the Azure modules version 1.3.2 and seems to be working with no modifications.

Thank you again,
-e
