### ISSUE TITLE
Hangs with a "WARNING: GeoReplicationEnabled property ...." message

### ISSUE THREAD

**Issue by simonmerrell** [fullscale180/asm2arm#4]
Thanks for creating these scripts, they look just what I need. 

I guess this is a basic error, but I can't seem to get started. If I run Add-AzureSMVmToRM then the script just hangs after this message:
"WARNING: GeoReplicationEnabled property will be deprecated in a future release of Azure PowerShell. The value will be merged into the AccountType property."

And then a flashing cursor, and nothing further, until I break out.

Any ideas? Any way to run more verbose so I can see where it gets stuck?

Thanks

**Comment by Ercenk** [comment]
Hello,
We have discovered a bug in our wait algorithm that is checking whether the storage account has been created or not. Although the message you are mentioning above is not related with it, the flashing cursor was. The issue must be resolved now, please check again.

Thank you for using our tool.
