### ISSUE TITLE
ARM Blob container was not created

### ISSUE THREAD

**Issue by richiero** [fullscale180/asm2arm#6]
I received a success message after executing the transfer however no files were visible in the azure portal.

_PS C:\asm2arm-master> $blob1 = Start-AzureStorageBlobCopy -Context $srcContext -AbsoluteUri $srcVhd -DestContainer $destContainerName -DestBlob $destVhdName -DestContex
t $destContext -Verbose
## VERBOSE: Transfer Summary

Total:  1.
Successful: 1.
Failed: 0.

$blob1 | Get-AzureStorageBlobCopyState_ command would produce nothing

I realized later that this was due to the missing container (in my case "vhds') in the blob.  After adding it manually the blob was copied properly.   Note that I had previously set $destContainerName = "vhds"

Not sure if this is a bug or perhaps something that should be added to the doc.

**Comment by Ercenk** [comment]
Hello,
That value is set to "vhds" as a default in the Globalsettings.ps1 file, included by the module manifest file and executed when you do Import-Module. Did you run the generated scripts on a different box, or before importing the module?
