### ISSUE TITLE
Can not install Modul

### ISSUE THREAD

**Issue by robbierage** [fullscale180/asm2arm#9]
Import-Module : Die Methode "get_DefaultContext" im Typ "Microsoft.Azure.Commands.Profile.EnableAzureRmDataCollectionCommand" der Assembly 
"Microsoft.Azure.Commands.Profile, Version=1.0.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" hat keine Implementierung.
In Zeile:1 Zeichen:1
- Import-Module .\asm2arm.psd1
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Import-Module], TypeLoadException
  - FullyQualifiedErrorId : System.TypeLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by Ercenk** [comment]
Hello,
Are you still seeing this error? If yes, could you please provide more details, by adding the -verbose switch?
Thanks,
-e
